# Generated by Django 4.2.3 on 2023-08-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('wingspan', models.CharField(max_length=50)),
                ('colors', models.CharField(max_length=50)),
            ],
        ),
    ]
